---
APP_KEY: "abc"
DB_PASSWORD: "abc"
PAYU_API_KEY: "abc"
PAYU_API_LOGIN: "abc"
BUGSNAG_API_KEY: "abc"
MIX_PANEL_TOKEN: "abc"
S3-KEY: "abc"
S3-SECRET: "abc"
AWS_KEY: "abc"
AWS_SECRET: "abc"
SES_KEY: "abc"
SES_SECRET: "abc"
DB_ROOT_PASSWORD: "abc"

IAM_s3mysql_ACCESS_KEY: "abc"
IAM_s3mysql_SECRET_KEY: "abc"

