---
- name: Provision Server
  hosts: server
  become: yes
  remote_user: "{{remote_user}}"
  roles:
    - { role: prerequisites }
    - { role: php }
    - { role: node }
    - { role: redis }
    - { role: nginx }
    - { role: supervisor }
    - { role: mysql }

