---
- name: provision server
  hosts: server
  become: Yes
  remote_user: ubuntu
  vars:
    base_domain_name: server.com
    main_domain_name: www.server.com
    enviroment: production
  roles:
    - { role: set-config }
    - { role: prerequisites }
    - { role: deimosfr.mariadb }
    - { role: jpnewman.redis }
    - { role: php }
    - { role: nginx }
    - { role: code }
    - { role: mariadb-backup, when: "cron is defined and cron == 'yes'" }
    - { role: cron, when: "cron is defined and cron == 'yes'" }
    - { role: youbond.supervisor}
    - { role: supervisor-config, when: "supervisor is defined and supervisor == 'yes'"}






