Vagrant.configure("2") do |config|
  config.vm.define :laravel do |laravel_config|
      laravel_config.vm.box = "ubuntu/jammy64"
      laravel_config.vm.hostname = "laravel"
      laravel_config.vm.network :private_network, ip: "192.168.56.10"

      # Port forwarding
      laravel_config.vm.network "forwarded_port", guest: 22, host: 2200
      laravel_config.vm.network "forwarded_port", guest: 3306, host: 3306
      laravel_config.vm.network "forwarded_port", guest: 80, host: 8080

      laravel_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end

      # Copiar la llave SSH al archivo authorized_keys
      laravel_config.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/temp_key"
      laravel_config.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~/.ssh
        cat /home/vagrant/.ssh/temp_key >> /home/vagrant/.ssh/authorized_keys
        rm /home/vagrant/.ssh/temp_key
      SHELL
  end
end