---
- name: include secrets
  include_vars:
    file: "secrets/{{ enviroment }}.yml"
    name: secrets

- name: include config
  include_vars:
    file: "config/{{ enviroment }}.yml"
    name: config
